local M = {}

M.ANIMAL_COMPANION_BADGER   = 0
M.ANIMAL_COMPANION_WOLF     = 1
M.ANIMAL_COMPANION_BEAR     = 2
M.ANIMAL_COMPANION_BOAR     = 3
M.ANIMAL_COMPANION_HAWK     = 4
M.ANIMAL_COMPANION_PANTHER  = 5
M.ANIMAL_COMPANION_SPIDER   = 6
M.ANIMAL_COMPANION_DIREWOLF = 7
M.ANIMAL_COMPANION_DIRERAT  = 8
M.ANIMAL_COMPANION_NONE     = 255

M.FAMILIAR_BAT        = 0
M.FAMILIAR_CRAGCAT    = 1
M.FAMILIAR_HELLHOUND  = 2
M.FAMILIAR_IMP        = 3
M.FAMILIAR_FIREMEPHIT = 4
M.FAMILIAR_ICEMEPHIT  = 5
M.FAMILIAR_PIXIE      = 6
M.FAMILIAR_RAVEN           = 7
M.FAMILIAR_FAIRY_DRAGON    = 8
M.FAMILIAR_PSEUDO_DRAGON    = 9
M.FAMILIAR_EYEBALL          = 10
M.FAMILIAR_NONE       = 255

-- These must match the values in nwscreature.h and nwccreaturemenu.cpp
-- Cannot use the value -1 because that is used to start a conversation
M.COMMAND_STANDGROUND             = -2
M.COMMAND_ATTACKNEAREST           = -3
M.COMMAND_HEALMASTER              = -4
M.COMMAND_FOLLOWMASTER            = -5
M.COMMAND_MASTERFAILEDLOCKPICK    = -6
M.COMMAND_GUARDMASTER             = -7
M.COMMAND_UNSUMMONFAMILIAR        = -8
M.COMMAND_UNSUMMONANIMALCOMPANION = -9
M.COMMAND_UNSUMMONSUMMONED        = -10
M.COMMAND_MASTERUNDERATTACK       = -11
M.COMMAND_RELEASEDOMINATION       = -12
M.COMMAND_UNPOSSESSFAMILIAR       = -13
M.COMMAND_MASTERSAWTRAP           = -14
M.COMMAND_MASTERATTACKEDOTHER     = -15
M.COMMAND_MASTERGOINGTOBEATTACKED = -16
M.COMMAND_LEAVEPARTY              = -17
M.COMMAND_PICKLOCK                = -18
M.COMMAND_INVENTORY               = -19
M.COMMAND_DISARMTRAP              = -20
M.COMMAND_TOGGLECASTING           = -21
M.COMMAND_TOGGLESTEALTH           = -22
M.COMMAND_TOGGLESEARCH            = -23

-- These match the values in nwscreature.h
M.NONE             = 0
M.HENCHMAN         = 1
M.ANIMALCOMPANION  = 2
M.FAMILIAR         = 3
M.SUMMONED         = 4
M.DOMINATED        = 5

return M