local M = {}

M.const = {
   CAMERA_MODE_CHASE_CAMERA          = 0,
   CAMERA_MODE_TOP_DOWN              = 1,
   CAMERA_MODE_STIFF_CHASE_CAMERA    = 2,

   CAMERA_TRANSITION_TYPE_SNAP = 0,
   CAMERA_TRANSITION_TYPE_CRAWL = 2,
   CAMERA_TRANSITION_TYPE_VERY_SLOW = 5,
   CAMERA_TRANSITION_TYPE_SLOW = 20,
   CAMERA_TRANSITION_TYPE_MEDIUM = 40,
   CAMERA_TRANSITION_TYPE_FAST = 70,
   CAMERA_TRANSITION_TYPE_VERY_FAST = 100,

   FADE_SPEED_SLOWEST = 0.003,
   FADE_SPEED_SLOW = 0.005,
   FADE_SPEED_MEDIUM = 0.01,
   FADE_SPEED_FAST = 0.017,
   FADE_SPEED_FASTEST = 0.25,
}

setmetatable(M, { __index = M.const })

return M