local M = {}

M.CAMERA_MODE_CHASE_CAMERA          = 0
M.CAMERA_MODE_TOP_DOWN              = 1
M.CAMERA_MODE_STIFF_CHASE_CAMERA    = 2

M.CAMERA_TRANSITION_TYPE_SNAP = 0
M.CAMERA_TRANSITION_TYPE_CRAWL = 2
M.CAMERA_TRANSITION_TYPE_VERY_SLOW = 5
M.CAMERA_TRANSITION_TYPE_SLOW = 20
M.CAMERA_TRANSITION_TYPE_MEDIUM = 40
M.CAMERA_TRANSITION_TYPE_FAST = 70
M.CAMERA_TRANSITION_TYPE_VERY_FAST = 100

M.FADE_SPEED_SLOWEST = 0.003
M.FADE_SPEED_SLOW = 0.005
M.FADE_SPEED_MEDIUM = 0.01
M.FADE_SPEED_FAST = 0.017
M.FADE_SPEED_FASTEST = 0.25
