local M = require 'solstice.objects.init'
safe_require 'solstice.objects.object'
safe_require 'solstice.objects.aoe'
safe_require 'solstice.objects.area'
safe_require 'solstice.objects.creature'
safe_require 'solstice.objects.door'
safe_require 'solstice.objects.encounter'
safe_require 'solstice.objects.item'
safe_require 'solstice.objects.module'
safe_require 'solstice.objects.placeable'
safe_require 'solstice.objects.sound'
safe_require 'solstice.objects.store'
safe_require 'solstice.objects.sound'
safe_require 'solstice.objects.trap'
safe_require 'solstice.objects.trigger'
safe_require 'solstice.objects.waypoint'
return M
