-- Skill defines
nwn.SKILL_ANIMAL_EMPATHY   = 0
nwn.SKILL_CONCENTRATION    = 1
nwn.SKILL_DISABLE_TRAP     = 2
nwn.SKILL_DISCIPLINE       = 3
nwn.SKILL_HEAL             = 4
nwn.SKILL_HIDE             = 5
nwn.SKILL_LISTEN           = 6
nwn.SKILL_LORE             = 7
nwn.SKILL_MOVE_SILENTLY    = 8
nwn.SKILL_OPEN_LOCK        = 9
nwn.SKILL_PARRY            = 10
nwn.SKILL_PERFORM          = 11
nwn.SKILL_PERSUADE         = 12
nwn.SKILL_PICK_POCKET      = 13
nwn.SKILL_SEARCH           = 14
nwn.SKILL_SET_TRAP         = 15
nwn.SKILL_SPELLCRAFT       = 16
nwn.SKILL_SPOT             = 17
nwn.SKILL_TAUNT            = 18
nwn.SKILL_USE_MAGIC_DEVICE = 19
nwn.SKILL_APPRAISE         = 20
nwn.SKILL_TUMBLE           = 21
nwn.SKILL_CRAFT_TRAP       = 22
nwn.SKILL_BLUFF            = 23
nwn.SKILL_INTIMIDATE       = 24
nwn.SKILL_CRAFT_ARMOR      = 25
nwn.SKILL_CRAFT_WEAPON     = 26
nwn.SKILL_RIDE             = 27
nwn.SKILL_LAST             = 27

nwn.SKILL_ALL_SKILLS       = 255

nwn.SUBSKILL_FLAGTRAP      = 100
nwn.SUBSKILL_RECOVERTRAP   = 101
nwn.SUBSKILL_EXAMINETRAP   = 102
